### ISSUE TITLE
Plugin must be packaged and installed correctly

### ISSUE THREAD

**Issue by rickbrew** [WhelanB/PDN-RemoveBG#1]
I just had to remove the link to your plugin on the forum because with the release of PDN 4.3 using .NET 5, plugins that have additional DLL dependencies need some new changes. I've listed the needs here: https://forums.getpaint.net/topic/118742-removebg-integration-effect/?do=findComment&comment=587162

The first step is to convert your csproj to the newer "SDK" style of project. You can use the `try-convert` tool to do this. You'll need to then target .NET 5, and make sure your plugin is installed to its own folder within Effects, and you'll want to include the `.deps.json` file.

Paint.NET also uses NewtonsoftJson.dll, so this is very important to make sure that the two don't conflict -- especially to ensure when your plugin is installed on newer (future) versions of Paint.NET, which will include newer versions of NewtonsoftJson, that your plugin doesn't break. Or that other plugins break; because they could also want to use a different version of the DLL. We don't want to get into ye ol' "DLL hell".

Happy to answer any questions, I realize this is a brand new requirement I'm dumping in your lap.

**Comment by rickbrew** [comment]
More discussion here, https://forums.getpaint.net/topic/118743-new-packaging-requirements-for-plugins-starting-with-pdn-43-net-5/

**Comment by WhelanB** [comment]
Great, thanks for sharing the new requirements! I had originally targeted this against PDN 4.2, but have bumped the version to 4.3 and started targeting .NET 5 in [WhelanB/target-pdn-43-net-5](https://github.com/WhelanB/PDN-RemoveBG/tree/WhelanB/target-pdn-43-net-5) - will open a PR shortly and generate a new release

thanks!

**Comment by WhelanB** [comment]
The changes have been merged in [this PR](https://github.com/WhelanB/PDN-RemoveBG/pull/2)
also migrated to System.Text.Json as suggested by toe_head2001 on the forums

Will add an additional release shortly, thanks for all your help!

**Comment by rickbrew** [comment]
btw I updated the forum post to link to the releases page at this repo https://forums.getpaint.net/topic/118742-removebg-integration-effect/
